# Generated by Django 4.2 on 2026-01-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='text',
            field=models.JSONField(),
        ),
    ]
