# Generated by Django 4.2 on 2026-01-18 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_journal_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='text',
            new_name='logs',
        ),
    ]
