# Generated by Django 4.2 on 2026-01-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('journal', '0004_rename_text_journal_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='tag',
            field=models.ManyToManyField(related_name='tagged_journals', to='tag.tag'),
        ),
    ]
