services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks: 
      - journal_network

  # web:
  #   build: .
  #   env_file:
  #     - .env
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #   networks: 
  #     - journal_network

volumes:
  postgres_data:

networks:
  journal_network:
