# Generated by Django 4.2 on 2025-06-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('conditions', models.CharField(max_length=300)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'ordering': ('topic',),
            },
        ),
    ]
