# Generated by Django 4.2 on 2025-06-17 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0002_achievement_journal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='achievement',
            old_name='topic',
            new_name='name',
        ),
    ]
